[package]
name = "domain_matcher"
version = "0.1.0"
authors = ["darsvador"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deepsize = "0.2.0"

